input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["app-logs", "notification", "registration"]
    codec => json
    group_id => "logstash-elk-group"
    decorate_events => true
    auto_offset_reset => "earliest"
  }
}

filter {
  # Парсим timestamp если он есть в сообщении
  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601", "yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
    }
  }

  # Добавляем имя топика как отдельное поле для удобства поиска в Kibana
  mutate {
    add_field => { "kafka_topic" => "%{[@metadata][kafka][topic]}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][kafka][topic]}-%{+YYYY.MM.dd}"
  }

  # Для отладки можно раскомментировать
  # stdout { codec => rubydebug }
}