input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["app-logs", "notification", "registration"]
    codec => json
    group_id => "logstash-group"
  }
}

filter {
  date {
    match => ["timestamp", "ISO8601"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][kafka][topic]}-%{+YYYY.MM.dd}"
  }
}